export interface BeforeAfterPair {
  title: string
  before: string
  after: string
  description?: string
}

export interface Project {
  id: string
  slug: string
  title: string
  subtitle?: string
  location: string
  type: string
  year: string
  featured?: boolean
  description: string
  credits: { role: string; name: string }[]
  coverImage: string
  heroImage: string
  images: string[]
  beforeAfter?: BeforeAfterPair[]
  highlights?: string[]
}

export const projects: Project[] = [
  {
    id: '1',
    slug: 'rockaway-retreat',
    title: 'Rockaway Retreat',
    subtitle: 'Coastal-Inspired Desert Living',
    location: 'Desert Color, St. George, Utah',
    type: 'Residential - Custom Home',
    year: '2025',
    featured: true,
    description: 'This home brings Rockaway Beach inspiration inside with warm woods, textured fabrics, and calming greens. Every room balances comfort and refinement, creating spaces that feel open, grounded, and welcoming. Designed for hosting and connection, it embraces natural light and easy indoor–outdoor living.',
    credits: [
      { role: 'Contractor', name: 'Cedar Pointe Homes' },
      { role: 'Photographer', name: 'Lacey Alexander' },
      { role: 'Interior Design', name: 'Parkway East Design' },
      { role: 'Architect', name: 'Shawn R. Patten' },
    ],
    coverImage: '/projects/04-rockaway-retreat/images/LCA_6968-Edit.webp',
    heroImage: '/projects/04-rockaway-retreat/images/7577-1920x1080-1.webp',
    images: [
      '/projects/04-rockaway-retreat/images/LCA_6968-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_6968-Edit-2.webp',
      '/projects/04-rockaway-retreat/images/LCA_7017-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7024.webp',
      '/projects/04-rockaway-retreat/images/LCA_7027.webp',
      '/projects/04-rockaway-retreat/images/LCA_7036.webp',
      '/projects/04-rockaway-retreat/images/LCA_7077-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7111-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7285-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7316-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7324-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7336-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7351-Edit-2.webp',
      '/projects/04-rockaway-retreat/images/LCA_7364.webp',
      '/projects/04-rockaway-retreat/images/LCA_7376.webp',
      '/projects/04-rockaway-retreat/images/LCA_7387-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7422-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7432-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7462-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7467.webp',
      '/projects/04-rockaway-retreat/images/LCA_7489-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7511-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7519-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7531-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7593-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7608-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7619-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7628-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7639.webp',
      '/projects/04-rockaway-retreat/images/LCA_7659-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7670-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7681-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7688-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7700-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7710-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7717-Edit-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7744-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7758-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7769-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7786-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7822-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7836.webp',
      '/projects/04-rockaway-retreat/images/LCA_7843-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7849-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7863-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7886-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7901-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7913-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7948-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7957-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7965.webp',
      '/projects/04-rockaway-retreat/images/LCA_7976-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7994-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_7997-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8010.webp',
      '/projects/04-rockaway-retreat/images/LCA_8077-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8089-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8111-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8124-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8136-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8153-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8165-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8194-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8204.webp',
      '/projects/04-rockaway-retreat/images/LCA_8212.webp',
      '/projects/04-rockaway-retreat/images/LCA_8229-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8250-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8282-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8289-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8307-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8356-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8366-Edit.webp',
      '/projects/04-rockaway-retreat/images/LCA_8379.webp',
    ],
    highlights: [
      'Coastal-inspired retreat design',
      'Golf simulator & home theater',
      'Resort-style pool',
      'Seamless indoor-outdoor living',
    ],
  },
  {
    id: '2',
    slug: 'crowded-table',
    title: 'Crowded Table',
    subtitle: 'Where Connection Lives',
    location: 'WestGate, St. George, Utah',
    type: 'Residential - Custom Home',
    year: '2025',
    featured: true,
    description: 'At Crowded Table, deliberate design and refined finishes unfold across 9,019 square feet of seamless indoor-outdoor living. Five private bedroom suites, two thoughtfully designed levels, and generous gathering spaces create a home centered on connection.',
    credits: [
      { role: 'Contractor', name: 'Jensen and Sons' },
      { role: 'Photographer', name: 'Lacey Alexander' },
      { role: 'Interior Design', name: 'Parkway East Design' },
      { role: 'Architect', name: 'Shawn R. Patten' },
    ],
    coverImage: '/projects/03-crowded-table/images/LCA_1120-.webp',
    heroImage: '/projects/03-crowded-table/images/LCA_1177.webp',
    images: [
      '/projects/03-crowded-table/images/LCA_1120-.webp',
      '/projects/03-crowded-table/images/LCA_1132-.webp',
      '/projects/03-crowded-table/images/LCA_1177.webp',
      '/projects/03-crowded-table/images/LCA_1202-.webp',
      '/projects/03-crowded-table/images/LCA_1233-.webp',
      '/projects/03-crowded-table/images/LCA_1257-.webp',
      '/projects/03-crowded-table/images/LCA_1272-.webp',
      '/projects/03-crowded-table/images/LCA_1285-.webp',
      '/projects/03-crowded-table/images/LCA_1301-.webp',
      '/projects/03-crowded-table/images/LCA_1388-.webp',
      '/projects/03-crowded-table/images/LCA_1416-.webp',
      '/projects/03-crowded-table/images/LCA_1438-.webp',
      '/projects/03-crowded-table/images/LCA_1447-.webp',
      '/projects/03-crowded-table/images/LCA_1455-.webp',
      '/projects/03-crowded-table/images/LCA_1492-.webp',
      '/projects/03-crowded-table/images/LCA_1506-.webp',
      '/projects/03-crowded-table/images/LCA_1525-.webp',
      '/projects/03-crowded-table/images/LCA_1547-Edit.webp',
      '/projects/03-crowded-table/images/LCA_1555-.webp',
      '/projects/03-crowded-table/images/LCA_1565-.webp',
      '/projects/03-crowded-table/images/LCA_1602-.webp',
      '/projects/03-crowded-table/images/LCA_1612-.webp',
      '/projects/03-crowded-table/images/LCA_1620-.webp',
      '/projects/03-crowded-table/images/LCA_1655-.webp',
      '/projects/03-crowded-table/images/LCA_1664-.webp',
      '/projects/03-crowded-table/images/LCA_1672-.webp',
      '/projects/03-crowded-table/images/LCA_1730-.webp',
      '/projects/03-crowded-table/images/LCA_1743-1-1.webp',
      '/projects/03-crowded-table/images/LCA_1757-.webp',
      '/projects/03-crowded-table/images/LCA_1775-.webp',
      '/projects/03-crowded-table/images/LCA_1785-.webp',
      '/projects/03-crowded-table/images/LCA_1790-.webp',
      '/projects/03-crowded-table/images/LCA_1792-.webp',
      '/projects/03-crowded-table/images/LCA_1801-.webp',
      '/projects/03-crowded-table/images/LCA_1806-.webp',
      '/projects/03-crowded-table/images/LCA_1825-.webp',
      '/projects/03-crowded-table/images/LCA_1835.webp',
      '/projects/03-crowded-table/images/LCA_1846-.webp',
      '/projects/03-crowded-table/images/LCA_1872.webp',
      '/projects/03-crowded-table/images/LCA_1881.webp',
      '/projects/03-crowded-table/images/LCA_1899.webp',
      '/projects/03-crowded-table/images/LCA_1925-.webp',
      '/projects/03-crowded-table/images/LCA_1934-.webp',
      '/projects/03-crowded-table/images/LCA_1955-.webp',
      '/projects/03-crowded-table/images/LCA_1975-.webp',
      '/projects/03-crowded-table/images/LCA_1989-.webp',
      '/projects/03-crowded-table/images/LCA_1995-.webp',
      '/projects/03-crowded-table/images/LCA_2010-.webp',
      '/projects/03-crowded-table/images/LCA_2026-.webp',
      '/projects/03-crowded-table/images/LCA_2050.webp',
      '/projects/03-crowded-table/images/LCA_2054-.webp',
      '/projects/03-crowded-table/images/LCA_2076-2.webp',
      '/projects/03-crowded-table/images/LCA_2093-.webp',
      '/projects/03-crowded-table/images/LCA_2102-.webp',
      '/projects/03-crowded-table/images/LCA_2147.webp',
      '/projects/03-crowded-table/images/LCA_2270-.webp',
      '/projects/03-crowded-table/images/LCA_2277.webp',
      '/projects/03-crowded-table/images/LCA_2281-.webp',
      '/projects/03-crowded-table/images/LCA_2295-2.webp',
      '/projects/03-crowded-table/images/LCA_2317-.webp',
      '/projects/03-crowded-table/images/LCA_2333-.webp',
      '/projects/03-crowded-table/images/LCA_2355-.webp',
      '/projects/03-crowded-table/images/LCA_2367-.webp',
      '/projects/03-crowded-table/images/LCA_2419-.webp',
      '/projects/03-crowded-table/images/LCA_2429.webp',
      '/projects/03-crowded-table/images/LCA_2438-.webp',
      '/projects/03-crowded-table/images/LCA_2457-.webp',
    ],
    highlights: [
      '9,019 square feet',
      'Five private bedroom suites',
      'Resort-style pool',
      '2025 Parade of Homes',
    ],
  },
  {
    id: '3',
    slug: 'abby-manor',
    title: 'Abby Manor',
    subtitle: 'Sophisticated Farmhouse',
    location: 'Stone Cliff, St. George, Utah',
    type: 'Residential - Custom Home',
    year: '2024',
    featured: true,
    description: 'Filled with sentimental pieces, pops of bright color, and international influences, this gorgeous custom home built in Stone Cliff, St. George, is a variation of sophisticated farmhouse.',
    credits: [
      { role: 'Contractor', name: 'Jensen + Sons Construction' },
      { role: 'Photographer', name: 'Lacey Alexander' },
      { role: 'Interior Design', name: 'Parkway East Design' },
    ],
    coverImage: '/projects/02-abby-manor/images/LCA_2209--scaled.webp',
    heroImage: '/projects/02-abby-manor/images/LCA_2305-.webp',
    images: [
      '/projects/02-abby-manor/images/LCA_1916--scaled.webp',
      '/projects/02-abby-manor/images/LCA_1933--scaled.webp',
      '/projects/02-abby-manor/images/LCA_1943--scaled.webp',
      '/projects/02-abby-manor/images/LCA_1979--scaled.webp',
      '/projects/02-abby-manor/images/LCA_1990--scaled.webp',
      '/projects/02-abby-manor/images/LCA_1998--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2011--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2036-1-1-scaled.webp',
      '/projects/02-abby-manor/images/LCA_2071--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2106--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2124--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2142--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2156--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2188--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2209--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2244--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2265-1-1-scaled.webp',
      '/projects/02-abby-manor/images/LCA_2282--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2324-.webp',
      '/projects/02-abby-manor/images/LCA_2407--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2440-.webp',
      '/projects/02-abby-manor/images/LCA_2453-.webp',
      '/projects/02-abby-manor/images/LCA_2460-.webp',
      '/projects/02-abby-manor/images/LCA_2470-.webp',
      '/projects/02-abby-manor/images/LCA_2475-.webp',
      '/projects/02-abby-manor/images/LCA_2481-.webp',
      '/projects/02-abby-manor/images/LCA_2487-.webp',
      '/projects/02-abby-manor/images/LCA_2503-.webp',
      '/projects/02-abby-manor/images/LCA_2506-.webp',
      '/projects/02-abby-manor/images/LCA_2517-.webp',
      '/projects/02-abby-manor/images/LCA_2520-.webp',
      '/projects/02-abby-manor/images/LCA_2535-.webp',
      '/projects/02-abby-manor/images/LCA_2544-.webp',
      '/projects/02-abby-manor/images/LCA_2548--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2556--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2581-2jpg.webp',
      '/projects/02-abby-manor/images/LCA_2586--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2596-.webp',
      '/projects/02-abby-manor/images/LCA_2598-.webp',
      '/projects/02-abby-manor/images/LCA_2603--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2611-.webp',
      '/projects/02-abby-manor/images/LCA_2638--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2704--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2717--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2724--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2730--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2740--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2749--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2754--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2770--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2833--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2845--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2874--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2889--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2912--scaled.webp',
      '/projects/02-abby-manor/images/LCA_2928--scaled.webp',
    ],
    highlights: [
      'Modern farmhouse design',
      'International influences',
      'Sentimental pieces throughout',
      'Stone Cliff community',
    ],
  },
  {
    id: '4',
    slug: 'stella-project',
    title: 'The Stella Project',
    subtitle: 'Small Updates, Big Impact',
    location: 'Southern Utah',
    type: 'Residential - Refresh',
    year: '2023',
    description: 'Named after their beloved house cat, the Stella Project is a perfect example of how even a small update can refresh and enliven an entire home. After years living in their house, our client felt like it still didn\'t quite feel like home—it just needed a touch of warmth.',
    credits: [
      { role: 'Interior Design', name: 'Parkway East Design' },
    ],
    coverImage: '/projects/01-stella-project/images/Blog-Covers-7.webp',
    heroImage: '/projects/01-stella-project/images/IMG_0446-2.webp',
    beforeAfter: [
      {
        title: 'Entryway Transformation',
        before: '/projects/01-stella-project/images/Blog-Post-1000-X-1500-4.webp',
        after: '/projects/01-stella-project/images/Blog-Post-1000-X-1500-3.webp',
        description: 'As the first introduction into the home, we wanted to create an experience that was both warm and welcoming. A round mirror adds height and space, while a new rug creates a firmer visual foundation.',
      },
      {
        title: 'Living Room Transformation',
        before: '/projects/01-stella-project/images/IMG_0446-2.webp',
        after: '/projects/01-stella-project/images/IMG_0419-2.webp',
        description: 'Swivel chairs, thoughtful drapery, and mid-century modern accents with blues and oranges transformed this space into a perfect blend of sophistication and cozy family living.',
      },
    ],
    images: [
      '/projects/01-stella-project/images/IMG_0450_jpg-2.webp',
      '/projects/01-stella-project/images/IMG_0460-2.webp',
      '/projects/01-stella-project/images/IMG_0479_jpg-2.webp',
      '/projects/01-stella-project/images/20221107-IMG_0470.webp',
      '/projects/01-stella-project/images/Instagram-Landscape-Posts-6.webp',
    ],
    highlights: [
      'Before & after transformation',
      'Entryway refresh',
      'Living room update',
      'Family-friendly design',
    ],
  },
]

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug)
}

export function getFeaturedProjects(): Project[] {
  return projects.filter((p) => p.featured)
}
